### PR TITLE
fix #6: Cannot find git-hooks in Windows

### LINKED ISSUE #6: It keeps say 'Cannot find git-hooks. Did you install it?'
I just followed the turtorial to test, but it fails, and keep said 'Cannot find git-hooks. Did you install it?'.

My env is Windows 7 + node 0.12.7

Thanks.

### PR DESCRIPTION
**Pull request by zloylos**
@tarmolov ok?

### CODE REVIEW

**Comment by tarmolov** [comment]
It doesn't work in my virtual machine. It still says `Cannot find git-hooks`.

**Comment by zloylos** [comment]
I updated commit. Can you check again?

**Comment by tarmolov** [comment]
Nothing is changed.

```bash
gf -IEUser@ie6winxp ~/git-hooks-js (master) $ git commit -m "test"
[GIT-HOOKS ERROR] Cannot find module '....lib\git-hooks'
[GIT-HOOKS ERROR] Cannot find module '....lib\git-hooks'
[GIT-HOOKS ERROR] Cannot find module '....lib\git-hooks'
[GIT-HOOKS ERROR] Cannot find module '....lib\git-hooks'
[master 1d5c38f] test
```
The problem is with the following line.
```javascript
var gitHooksPath = '..\..\lib' + path.sep + 'git-hooks';
```
There are window backslashes but cygwin interprets them as unix world expects: backslashes escapes symbols. So `\.` means just `.`. That's why cygwin tried to look for a module in `....lib\git-hooks`.

Actually, it's not so easy to make `git-hooks` work on Windows.

The following issues should be taking into account:
  1. The program should work in Cygwin and PowerShell as well.
  2. All unix specific paths should be replaced with `path.resolve`.
  3. `spawn` works incorrectly on windows. So even a separate module [was created](https://www.npmjs.com/package/win-spawn).
  4. Maybe even something else because I'm not a Window user.

Anyway, 
We need to go deeper

**Comment by tarmolov** [comment]
#6

**Comment by codebling** [comment]
Should be fixed by #29.

**Comment by tarmolov** [comment]
Sorry for the huge delay with decision about Windows support. I decided keep support only for Unix and macOS. I can guarantee expected behaviour only on this platforms. 

And again I want to say sorry about negative decision.

**Pull request closed without merging**
