### PR TITLE
Allow execution on Windows

### PR DESCRIPTION
**Pull request by artptr**
Original pull request is https://github.com/tarmolov/git-hooks-js/pull/29 by @codebling
Just resolved a merge conflict.

### CODE REVIEW

**Comment by codebling** [comment]
Fixes merge issues with #29 

@tarmolov any update on merging Windows compatibility?

**Comment by tarmolov** [comment]
It'd be a great to add windows support to the library but I have three concerns about this and #29 prs:
  * platform specific code are mixed through all codebase
  * fix for `spawn` looks hacky and doesn't cover all cases (I've compared it with [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) library); adding partial support doesn't look as a good step
  * I use mac/unix and I cannot test windows specific code for each release; so, it can be broken from time to time (it seems that it can be solved by yet another third-party like https://www.appveyor.com)

**Comment by codebling** [comment]
This is good feedback. Looking back at the changes, they can be cleaned up a lot. Respectively,
 * Checking file permissions is a platform-specific operation, so another conditional is necessary whenever this happens. Testing permissions for executability seems like an anti-pattern to me, however. Simply try to execute the command, then catch-and-ignore any EACCES errors. In this way we could not only clean up the code by removing `isExecutable()`, but also make it Windows-compatible.
 * `cross-spawn` is unlikely to solve the issues related to spawning in the majority of cases. Commands like `exec('git check-ignore ')` would still require `git` to be in the PATH, which by default it is not. It may be worth testing to verify those statements.
 * Correct, appveyor seems to be the way to go for this.

**Comment by Regaddi** [comment]
Any progress on this?

**Comment by tarmolov** [comment]
Nope.

I can merge it as an experimental feature but I cannot guarantee that `git-hooks` will work fine on windows. See my comment above https://github.com/tarmolov/git-hooks-js/pull/38#issuecomment-271422549

**Comment by tarmolov** [comment]
Sorry for the huge delay with decision about Windows support. I decided keep support only for Unix and macOS. I can guarantee expected behaviour only on this platforms. 

And again I want to say sorry about negative decision.

**Comment by codebling** [comment]
No worries. Windows users can use my fork, I will update and maintain, time allowing.

**Comment by tarmolov** [comment]
I can add a link to your fork in README file.

**Comment by codebling** [comment]
Sounds good!

**Comment by tarmolov** [comment]
Let me know when you publish a first version.

**Comment by codebling** [comment]
There are a few PRs offering Windows support (see #11, #29, #38, #52 and your own #51) but it's unlikely that these will be merged, see tarmolov's comment [here](https://github.com/tarmolov/git-hooks-js/pull/38#issuecomment-271422549). Check out [Husky](https://github.com/typicode/husky), it's a very active project which allows you to set up git hooks in your package.json file. It supports OSX, linux and Windows and has support for a few other hooks which git-hooks-js does not.

**Pull request closed without merging**
