### PR TITLE
Allow execution on Windows

### PR DESCRIPTION
**Pull request by codebling**
There are 2 issues blocking windows execution: verifying execution bit and launching Unix-style scripts. This PR resolves both.

### CODE REVIEW

**Comment by codebling** [comment]
Didn't run tests like a noob. Fixed code style, will make tests Windows-friendly tomorrow.

**Comment by codebling** [comment]
Fixes #10

**Comment by codebling** [comment]
Because I created this PR from master, the changes in this PR now include the changes from #31. To only merge the Windows changes, pull from branch 'windows' instead. To merge #31 and windows, merge this PR.

**Comment by tarmolov** [comment]
Sorry for the huge delay with decision about Windows support. I decided keep support only for Unix and macOS. I can guarantee expected behaviour only on this platforms. 

And again I want to say sorry about negative decision.

**Comment by codebling** [comment]
Anyone looking for Windows support should check out [Husky](https://github.com/typicode/husky). It's a very active project which allows you to set up git hooks in your package.json file. It supports OSX, linux and Windows and has support for a few other hooks which git-hooks-js does not.

**Pull request closed without merging**
